### ISSUE TITLE
Cannot configure source directory in Kotlin DSL

### ISSUE THREAD

**Issue by paul-ilvez** [qaware/xsd2java-gradle-plugin#1]
I am using Gradle 5.4 with Kotlin DSL (I stress it - NOT Groovy).

I tried to follow the example in the readme as close as possible to configure the source directory so here's what I've configured:

<pre><code>configurations {
    xsd2java {
        closureOf&lt;XSD2JavaTask&gt; {
            schemas {
                schemaDirPath = File("src/main/resources/schemas")
                packageName = "com.foo.bar.template.model"
            }
        }
        extension = true
        arguments = listOf("-verbose")
    }</code></pre>

But every time I execute the xsd2javaClasses task all I see in the console is:

<pre><code>03:45:49: Executing task 'xsd2javaClasses'...

> Task :compileXsd2javaJava NO-SOURCE
> Task :processXsd2javaResources NO-SOURCE
> Task :xsd2javaClasses UP-TO-DATE

BUILD SUCCESSFUL in 0s
03:45:49: Task execution finished 'xsd2javaClasses'.</pre></code>

And needless to say, no generated Java classes in the package name I configured. What am I configuring wrong?

**Comment by lreimer** [comment]
Hey Paul, personally I have never used the Kotlin DSL. We will have a look at it.

**Comment by paul-ilvez** [comment]
What is the `printJobModel` closure in the example snippet? What should I substitute it with in my project?

**Comment by lreimer** [comment]
Hello Paul,
the `printJobModel` closure in the Groovy example is the name of a `NamedDomainObjectContainer`, so yes you need this. Just use a different name. 

The follow Kotlin DSL build script works for me. I have also updated the README.

```kotlin
plugins {
    id("de.qaware.gradle.plugin.xsd2java") version "1.0.0"
}

xsd2java {
    schemas {
        create("dummy") {
            schemaDirPath = file("src/main/resources/xsd").toPath()
            packageName = "de.qaware.gradle.plugin.xsd2java.dummy.xsd"
        }
    }
    
    extension = true
    arguments = listOf("-verbose")
    outputDir = file("${project.buildDir}/generated-sources/xsd2java")
}
```

**Comment by paul-ilvez** [comment]
Thanks! Worked for me. Probably it's a good idea to give code snippets for Gradle plugins in both Groovy and Kotlin DSL, since the latter is gaining momentum.
