### ISSUE TITLE
Dependency to configuration xsd2javaCompile is not setup correcly.

### ISSUE THREAD

**Issue by jutoft** [qaware/xsd2java-gradle-plugin#2]
When using eg xsd2javaCompile as a classpath in an ant task.
It is needed to manually declare a dependsOn for the task executing the ant task.

**Comment by jutoft** [comment]
Is this project still maintained?

**Comment by lreimer** [comment]
Sure. Thanks for the pull request. Will have a look at it.

**Comment by jutoft** [comment]
Would you be interested in updating the minimum supported version and start using Properties/Providers to cleanup the variables?
it would have to depend on version 6.0 i think.

**Comment by chr-fritz** [comment]
I will take a look on the supported gradle versions. Currently I think it is not possible to use it with newer Gradle versions.

Will be tracked in #4. So i will close this one.
