### ISSUE TITLE
Gradle 7.0 issue - compileConfigurationName no longer supported

### ISSUE THREAD

**Issue by twogood** [qaware/xsd2java-gradle-plugin#5]
`compileConfigurationName` was deprecated in Gradle 6. Now it is gone. I think it should be replaced by `compileClasspathConfigurationName`.

```
Welcome to Gradle 7.0!
Here are the highlights of this release:
 - File system watching enabled by default
 - Support for running with and building Java 16 projects
 - Native support for Apple Silicon processors
 - Dependency catalog feature preview
For more details see https://docs.gradle.org/7.0/release-notes.html
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.0/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build 
FAILURE: Build failed with an exception.
* Where:
Build file '/builds/XXXXXX/build.gradle.kts' line: 29
* What went wrong:
An exception occurred applying plugin request [id: 'de.qaware.gradle.plugin.xsd2java', version: '1.0.0']
> Failed to apply plugin 'de.qaware.gradle.plugin.xsd2java'.
   > Could not get unknown property 'compileConfigurationName' for source set 'xsd2java' of type org.gradle.api.internal.tasks.DefaultSourceSet.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 1m 31s
```

**Comment by lreimer** [comment]
Thanks for reporting this. Would you be willing to provide a possible fix as pull request?

**Comment by twogood** [comment]
No this time, sorry. We switched to https://github.com/bjornvester/xjc-gradle-plugin instead.

**Comment by johnpooley** [comment]
hello, I have raised a PR relating to this issue that I would love for you to take a look at and give me any feedback on. thanks!

**Comment by brookman** [comment]
Hello. This would really help us as well. Now that Java 17 with long time support is released we are thinking about a upgrade. This would require Gradle 7.2+.
Thanks!

**Comment by lreimer** [comment]
Sorry for the late reply. Back from holiday now.
Will have a look at the PR later this week and release a new version.

**Comment by lreimer** [comment]
Merged #7. Should work now. Will release a new plugin version.

**Comment by brookman** [comment]
@lreimer Sorry to bother you. Did you already release the new version? I think the version on plugins.gradle.org is still 2.0.0.

**Comment by lreimer** [comment]
2.1.0 has been uploaded to the plugin portal.
